config/routes.rb
Rails.application.routes.draw do
  get 'parser/show'

  resources :trainings
  get 'signup', to: 'users#new'
  post 'login', to: 'sessions#create'
  get 'login', to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'
  resources :users
  get 'page/index'
  root 'page#index'
  get '/users/:id/getid', to: 'users#getid', as: 'getid_user'
  resources :relationships, only: [:create, :destroy]
  resources :users do
    member do
      get :following, :followers
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/training.rb
class Training < ApplicationRecord
  belongs_to :user
  validates :count,
            presence: true
  validates :approaches,
            presence: true
  validates :comments,
            presence: false
  def to_s
    count
  end
end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController
  before_action :set_training, only: [:show, :edit, :update, :destroy]

  # GET /trainings
  # GET /trainings.json
  def index
    if current_user
    @trainings = current_user.trainings.all.order(created_at:'DESC')
    else
    redirect_to root_url
    end
  end

  # GET /trainings/1
  # GET /trainings/1.json
  def show
  end

  # GET /trainings/new
  def new
    @training = Training.new
  end

  # GET /trainings/1/edit
  def edit
  end

  # POST /trainings
  # POST /trainings.json
  def create
    @training = current_user.trainings.build(training_params)

    respond_to do |format|
      if @training.save
        format.html { redirect_to @training, notice: 'Training was successfully created.' }
        format.json { render :show, status: :created, location: @training }
      else
        format.html { render :new }
        format.json { render json: @training.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trainings/1
  # PATCH/PUT /trainings/1.json
  def update
    respond_to do |format|
      if @training.update(training_params)
        format.html { redirect_to @training, notice: 'Training was successfully updated.' }
        format.json { render :show, status: :ok, location: @training }
      else
        format.html { render :edit }
        format.json { render json: @training.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trainings/1
  # DELETE /trainings/1.json
  def destroy
    @training.destroy
    respond_to do |format|
      format.html { redirect_to trainings_url, notice: 'Training was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_training
      @training = Training.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def training_params
      params.require(:training).permit(:count, :approaches, :comments)
    end
end

app/helpers/trainings_helper.rb
module TrainingsHelper
end

app/views/trainings/_form.html.erb
<%= form_with(model: training, local: true) do |form| %>
  <% if training.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(training.errors.count, "error") %> prohibited this training from being saved:</h2>

      <ul>
      <% training.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%# <div class="field"> %>
    <%# <%= form.label :user_id %>
    <%# <%= form.text_field :user_id, id: :training_user_id %>
  <%# </div> %>

  <div class="field">
    <%= form.label "Количество" %>
    <%= form.number_field :count, id: :training_count %>
  </div>

  <div class="field">
    <%= form.label "Подходов"%>
    <%= form.number_field :approaches, id: :training_approaches %>
  </div>

  <div class="field">
    <%= form.label "Комментарии" %>
    <%= form.text_field :comments, id: :training_comments %>
  </div>

  <div class="actions">
    <%= form.submit "Завершить" %>
  </div>
<% end %>

app/views/trainings/edit.html.erb
<h1>Редактирование отжиманий</h1>

<%= render 'form', training: @training %>

<%= link_to 'Посмотреть', @training %> |
<%= link_to 'Назад', trainings_path %>

app/views/trainings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Отжимания</h1>

<table>
  <thead>
    <tr>
      <th>Пользователь</th>
      <th>Количество</th>
      <th>Подходов</th>
      <th>Комментарии</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trainings.each do |training| %>
      <tr>
        <td><%= training.user  %></td>
        <td><%= training.count %></td>
        <td><%= training.approaches %></td>
        <td><%= training.comments %></td>
        <td><%= link_to 'Посмотреть', training %></td>
        <td><%= link_to 'Изменить', edit_training_path(training) %></td>
        <td><%= link_to 'Удалить', training, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Отжаться', new_training_path %>

app/views/trainings/new.html.erb
<h1>Отжимаюсь</h1>

<%= render 'form', training: @training %>

<%= link_to 'Назад', trainings_path %>

app/views/trainings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Пользователь:</strong>
  <%= @training.user %>
</p>

<p>
  <strong>Количество:</strong>
  <%= @training.count %>
</p>

<p>
  <strong>Подходов:</strong>
  <%= @training.approaches %>
</p>

<p>
  <strong>Комментарии:</strong>
  <%= @training.comments %>
</p>

<%= link_to 'Изменить', edit_training_path(@training) %> |
<%= link_to 'Назад', trainings_path %>