config/routes.rb
Rails.application.routes.draw do
  get 'parser/show'

  resources :trainings
  get 'signup', to: 'users#new'
  post 'login', to: 'sessions#create'
  get 'login', to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'
  resources :users
  get 'page/index'
  root 'page#index'
  get '/users/:id/getid', to: 'users#getid', as: 'getid_user'
  resources :relationships, only: [:create, :destroy]
  resources :users do
    member do
      get :following, :followers
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pushupsbattle</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% flash.each do |key, value| %>
      <%= content_tag :div, value, class: "flash #{key}" %>
  <% end %>
  <header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light container">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    <%= link_to "Push Ups Battle", root_path , class: "navbar-brand"%>
    <% if current_user?%>
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <%= link_to "Отжимания", trainings_path, class:"nav-link"%>
      </li>
    </ul>
    <div class="form-inline my-2 my-lg-0">
      Вы вошли как <%= current_user.to_s%>
      Подписчиков: <%= current_user.followers.count%>,
      Подписок: <%= current_user.following.count%> <br>
      <%= link_to "Выйти", logout_path, class:"btn btn-outline-success my-2 my-sm-0"%>
    </div>
    <div class="form-inline my-2 my-lg-0">
    <% else %>
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <li class="nav-item active">

        </li>
      </ul>
      <%= link_to "Регистрация", signup_path, class:"btn btn-outline-primary mr-md-2"%>
      <%= link_to "Вход", login_path, class:"btn btn-outline-success my-2 my-sm-0"%>
    <% end %>
    </div>
  </div>
</nav>
  </div>

  </header>
    <div class="container">
    <%= yield %>
    </div>
  <footer class="container">
    by Veprev
  </footer>
  </body>
</html>